#build settings
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

title: shoulderhit.com
description: All your pro Go/Baduk/Weiqi needs

show_downloads: false

github:
  is_project_page: false
